package com.enchanted_realm.spritesheet;

import java.awt.image.BufferedImage;

import javax.annotation.Nonnull;

public enum SpriteSheet {
	BUTTONS_BTN01("buttons\\Btn01.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BTN02("buttons\\Btn02.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BTN03("buttons\\Btn03.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BTN04("buttons\\Btn04.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BTN05("buttons\\Btn05.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BTN06("buttons\\Btn06.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BTN07("buttons\\Btn07.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BTN08("buttons\\Btn08.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BTN09("buttons\\Btn09.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BTN10("buttons\\Btn10.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BUTTON01("buttons\\Button01.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BUTTON02("buttons\\Button02.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BUTTON03("buttons\\Button03.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BUTTON04("buttons\\Button04.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BUTTON05("buttons\\Button05.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BUTTON06("buttons\\Button06.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BUTTON07("buttons\\Button07.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BUTTON08("buttons\\Button08.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BUTTON09("buttons\\Button09.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BUTTON10("buttons\\Button10.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BUTTON11("buttons\\Button11.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BUTTON12("buttons\\Button12.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BUTTON13("buttons\\Button13.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BUTTON14("buttons\\Button14.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BUTTON15("buttons\\Button15.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BUTTON16("buttons\\Button16.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BUTTON17("buttons\\Button17.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BUTTON18("buttons\\Button18.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BUTTON19("buttons\\Button19.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BUTTON20("buttons\\Button20.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BUTTON21("buttons\\Button21.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BUTTON22("buttons\\Button22.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BUTTON23("buttons\\Button23.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BUTTON24("buttons\\Button24.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_BUTTON25("buttons\\Button25.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_CHECKBOX01("buttons\\CheckBox01.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_CHECKBOX02("buttons\\CheckBox02.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_CHECKBOX03("buttons\\CheckBox03.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_CHECKBOX04("buttons\\CheckBox04.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_CHECKBOX05("buttons\\CheckBox05.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_CHECKBOX06("buttons\\CheckBox06.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_CHECKBOX07("buttons\\CheckBox07.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_CHECKBOX08("buttons\\CheckBox08.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_CHECKBOX09("buttons\\CheckBox09.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_CHECKBOX10("buttons\\CheckBox10.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON01("buttons\\Icon01.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON02("buttons\\Icon02.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON03("buttons\\Icon03.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON04("buttons\\Icon04.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON05("buttons\\Icon05.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON06("buttons\\Icon06.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON07("buttons\\Icon07.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON08("buttons\\Icon08.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON09("buttons\\Icon09.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON10("buttons\\Icon10.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON100("buttons\\Icon100.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON101("buttons\\Icon101.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON102("buttons\\Icon102.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON103("buttons\\Icon103.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON104("buttons\\Icon104.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON105("buttons\\Icon105.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON11("buttons\\Icon11.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON12("buttons\\Icon12.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON13("buttons\\Icon13.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON14("buttons\\Icon14.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON15("buttons\\Icon15.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON16("buttons\\Icon16.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON17("buttons\\Icon17.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON18("buttons\\Icon18.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON19("buttons\\Icon19.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON20("buttons\\Icon20.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON21("buttons\\Icon21.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON22("buttons\\Icon22.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON23("buttons\\Icon23.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON24("buttons\\Icon24.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON25("buttons\\Icon25.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON26("buttons\\Icon26.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON27("buttons\\Icon27.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON28("buttons\\Icon28.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON29("buttons\\Icon29.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON30("buttons\\Icon30.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON31("buttons\\Icon31.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON32("buttons\\Icon32.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON33("buttons\\Icon33.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON34("buttons\\Icon34.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON35("buttons\\Icon35.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON36("buttons\\Icon36.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON37("buttons\\Icon37.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON38("buttons\\Icon38.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON39("buttons\\Icon39.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON40("buttons\\Icon40.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON41("buttons\\Icon41.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON42("buttons\\Icon42.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON43("buttons\\Icon43.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON44("buttons\\Icon44.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON45("buttons\\Icon45.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON46("buttons\\Icon46.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON47("buttons\\Icon47.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON48("buttons\\Icon48.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON49("buttons\\Icon49.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON50("buttons\\Icon50.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON51("buttons\\Icon51.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON52("buttons\\Icon52.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON53("buttons\\Icon53.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON54("buttons\\Icon54.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON55("buttons\\Icon55.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON56("buttons\\Icon56.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON57("buttons\\Icon57.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON58("buttons\\Icon58.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON59("buttons\\Icon59.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON60("buttons\\Icon60.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON61("buttons\\Icon61.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON62("buttons\\Icon62.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON63("buttons\\Icon63.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON64("buttons\\Icon64.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON65("buttons\\Icon65.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON66("buttons\\Icon66.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON67("buttons\\Icon67.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON68("buttons\\Icon68.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON69("buttons\\Icon69.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON70("buttons\\Icon70.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON71("buttons\\Icon71.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON72("buttons\\Icon72.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON73("buttons\\Icon73.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON74("buttons\\Icon74.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON75("buttons\\Icon75.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON76("buttons\\Icon76.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON77("buttons\\Icon77.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON78("buttons\\Icon78.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON79("buttons\\Icon79.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON80("buttons\\Icon80.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON81("buttons\\Icon81.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON82("buttons\\Icon82.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON83("buttons\\Icon83.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON84("buttons\\Icon84.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON85("buttons\\Icon85.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON86("buttons\\Icon86.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON87("buttons\\Icon87.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON88("buttons\\Icon88.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON89("buttons\\Icon89.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON90("buttons\\Icon90.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON91("buttons\\Icon91.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON92("buttons\\Icon92.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON93("buttons\\Icon93.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON94("buttons\\Icon94.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON95("buttons\\Icon95.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON96("buttons\\Icon96.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON97("buttons\\Icon97.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON98("buttons\\Icon98.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_ICON99("buttons\\Icon99.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_MSG01("buttons\\Msg01.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_MSG02("buttons\\Msg02.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_MSG03("buttons\\Msg03.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_MSG04("buttons\\Msg04.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_MSG05("buttons\\Msg05.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_MSG06("buttons\\Msg06.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_MSG07("buttons\\Msg07.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_MSG08("buttons\\Msg08.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_MSG09("buttons\\Msg09.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_MSG10("buttons\\Msg10.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_MSG11("buttons\\Msg11.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_MSG12("buttons\\Msg12.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_MSG13("buttons\\Msg13.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_MSG14("buttons\\Msg14.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_MSG15("buttons\\Msg15.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_MSG16("buttons\\Msg16.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_MSG17("buttons\\Msg17.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_MSG18("buttons\\Msg18.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_MSG19("buttons\\Msg19.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_MSG20("buttons\\Msg20.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER01("buttons\\Number01.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER02("buttons\\Number02.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER03("buttons\\Number03.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER04("buttons\\Number04.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER05("buttons\\Number05.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER06("buttons\\Number06.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER07("buttons\\Number07.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER08("buttons\\Number08.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER09("buttons\\Number09.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER10("buttons\\Number10.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER11("buttons\\Number11.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER12("buttons\\Number12.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER13("buttons\\Number13.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER14("buttons\\Number14.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER15("buttons\\Number15.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER16("buttons\\Number16.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER17("buttons\\Number17.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER18("buttons\\Number18.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER19("buttons\\Number19.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER20("buttons\\Number20.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER21("buttons\\Number21.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER22("buttons\\Number22.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER23("buttons\\Number23.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER24("buttons\\Number24.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER25("buttons\\Number25.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER26("buttons\\Number26.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER27("buttons\\Number27.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER28("buttons\\Number28.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER29("buttons\\Number29.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER30("buttons\\Number30.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER31("buttons\\Number31.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER32("buttons\\Number32.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER33("buttons\\Number33.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER34("buttons\\Number34.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER35("buttons\\Number35.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER36("buttons\\Number36.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER37("buttons\\Number37.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER38("buttons\\Number38.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER39("buttons\\Number39.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER40("buttons\\Number40.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER41("buttons\\Number41.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER42("buttons\\Number42.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER43("buttons\\Number43.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER44("buttons\\Number44.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_NUMBER45("buttons\\Number45.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_PROGRESS01("buttons\\Progress01.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_PROGRESS02("buttons\\Progress02.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_PROGRESS03("buttons\\Progress03.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_PROGRESS04("buttons\\Progress04.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_PROGRESS05("buttons\\Progress05.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_SLIDER01("buttons\\Slider01.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_SLIDER02("buttons\\Slider02.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_SLIDER03("buttons\\Slider03.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_SLIDER04("buttons\\Slider04.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_SLIDER05("buttons\\Slider05.png", new SpriteSheetProperties(false, 16)),
	BUTTONS_SLIDERBAR_PROGRESSBAR("buttons\\SliderBar_ProgressBar.png", new SpriteSheetProperties(false, 16)),
	CAT_1_CAT_1_IDLE("Cat-1\\Cat-1-Idle.png", new SpriteSheetProperties(false, 16)),
	CAT_1_CAT_1_ITCH("Cat-1\\Cat-1-Itch.png", new SpriteSheetProperties(false, 16)),
	CAT_1_CAT_1_LAYING("Cat-1\\Cat-1-Laying.png", new SpriteSheetProperties(false, 16)),
	CAT_1_CAT_1_LICKING_1("Cat-1\\Cat-1-Licking 1.png", new SpriteSheetProperties(false, 16)),
	CAT_1_CAT_1_LICKING_2("Cat-1\\Cat-1-Licking 2.png", new SpriteSheetProperties(false, 16)),
	CAT_1_CAT_1_MEOW("Cat-1\\Cat-1-Meow.png", new SpriteSheetProperties(false, 16)),
	CAT_1_CAT_1_RUN("Cat-1\\Cat-1-Run.png", new SpriteSheetProperties(false, 16)),
	CAT_1_CAT_1_SITTING("Cat-1\\Cat-1-Sitting.png", new SpriteSheetProperties(false, 16)),
	CAT_1_CAT_1_SLEEPING1("Cat-1\\Cat-1-Sleeping1.png", new SpriteSheetProperties(false, 16)),
	CAT_1_CAT_1_SLEEPING2("Cat-1\\Cat-1-Sleeping2.png", new SpriteSheetProperties(false, 16)),
	CAT_1_CAT_1_STRETCHING("Cat-1\\Cat-1-Stretching.png", new SpriteSheetProperties(false, 16)),
	CAT_1_CAT_1_WALK("Cat-1\\Cat-1-Walk.png", new SpriteSheetProperties(false, 16)),
	CAT_2_CAT_2_IDLE("Cat-2\\Cat-2-Idle.png", new SpriteSheetProperties(false, 16)),
	CAT_2_CAT_2_ITCH("Cat-2\\Cat-2-Itch.png", new SpriteSheetProperties(false, 16)),
	CAT_2_CAT_2_LAYING("Cat-2\\Cat-2-Laying.png", new SpriteSheetProperties(false, 16)),
	CAT_2_CAT_2_LICKING_1("Cat-2\\Cat-2-Licking 1.png", new SpriteSheetProperties(false, 16)),
	CAT_2_CAT_2_LICKING_2("Cat-2\\Cat-2-Licking 2.png", new SpriteSheetProperties(false, 16)),
	CAT_2_CAT_2_MEOW("Cat-2\\Cat-2-Meow.png", new SpriteSheetProperties(false, 16)),
	CAT_2_CAT_2_RUN("Cat-2\\Cat-2-Run.png", new SpriteSheetProperties(false, 16)),
	CAT_2_CAT_2_SITTING("Cat-2\\Cat-2-Sitting.png", new SpriteSheetProperties(false, 16)),
	CAT_2_CAT_2_SLEEPING1("Cat-2\\Cat-2-Sleeping1.png", new SpriteSheetProperties(false, 16)),
	CAT_2_CAT_2_SLEEPING2("Cat-2\\Cat-2-Sleeping2.png", new SpriteSheetProperties(false, 16)),
	CAT_2_CAT_2_STRETCHING("Cat-2\\Cat-2-Stretching.png", new SpriteSheetProperties(false, 16)),
	CAT_2_CAT_2_WALK("Cat-2\\Cat-2-Walk.png", new SpriteSheetProperties(false, 16)),
	CAT_3_CAT_3_IDLE("Cat-3\\Cat-3-Idle.png", new SpriteSheetProperties(false, 16)),
	CAT_3_CAT_3_ITCH("Cat-3\\Cat-3-Itch.png", new SpriteSheetProperties(false, 16)),
	CAT_3_CAT_3_LAYING("Cat-3\\Cat-3-Laying.png", new SpriteSheetProperties(false, 16)),
	CAT_3_CAT_3_LICKING_1("Cat-3\\Cat-3-Licking 1.png", new SpriteSheetProperties(false, 16)),
	CAT_3_CAT_3_LICKING_2("Cat-3\\Cat-3-Licking 2.png", new SpriteSheetProperties(false, 16)),
	CAT_3_CAT_3_MEOW("Cat-3\\Cat-3-Meow.png", new SpriteSheetProperties(false, 16)),
	CAT_3_CAT_3_RUN("Cat-3\\Cat-3-Run.png", new SpriteSheetProperties(false, 16)),
	CAT_3_CAT_3_SITTING("Cat-3\\Cat-3-Sitting.png", new SpriteSheetProperties(false, 16)),
	CAT_3_CAT_3_SLEEPING1("Cat-3\\Cat-3-Sleeping1.png", new SpriteSheetProperties(false, 16)),
	CAT_3_CAT_3_SLEEPING2("Cat-3\\Cat-3-Sleeping2.png", new SpriteSheetProperties(false, 16)),
	CAT_3_CAT_3_STRETCHING("Cat-3\\Cat-3-Stretching.png", new SpriteSheetProperties(false, 16)),
	CAT_3_CAT_3_WALK("Cat-3\\Cat-3-Walk.png", new SpriteSheetProperties(false, 16)),
	CAT_4_CAT_4_IDLE("Cat-4\\Cat-4-Idle.png", new SpriteSheetProperties(false, 16)),
	CAT_4_CAT_4_ITCH("Cat-4\\Cat-4-Itch.png", new SpriteSheetProperties(false, 16)),
	CAT_4_CAT_4_LAYING("Cat-4\\Cat-4-Laying.png", new SpriteSheetProperties(false, 16)),
	CAT_4_CAT_4_LICKING_1("Cat-4\\Cat-4-Licking 1.png", new SpriteSheetProperties(false, 16)),
	CAT_4_CAT_4_LICKING_2("Cat-4\\Cat-4-Licking 2.png", new SpriteSheetProperties(false, 16)),
	CAT_4_CAT_4_MEOW("Cat-4\\Cat-4-Meow.png", new SpriteSheetProperties(false, 16)),
	CAT_4_CAT_4_RUN("Cat-4\\Cat-4-Run.png", new SpriteSheetProperties(false, 16)),
	CAT_4_CAT_4_SITTING("Cat-4\\Cat-4-Sitting.png", new SpriteSheetProperties(false, 16)),
	CAT_4_CAT_4_SLEEPING1("Cat-4\\Cat-4-Sleeping1.png", new SpriteSheetProperties(false, 16)),
	CAT_4_CAT_4_SLEEPING2("Cat-4\\Cat-4-Sleeping2.png", new SpriteSheetProperties(false, 16)),
	CAT_4_CAT_4_STRETCHING("Cat-4\\Cat-4-Stretching.png", new SpriteSheetProperties(false, 16)),
	CAT_4_CAT_4_WALK("Cat-4\\Cat-4-Walk.png", new SpriteSheetProperties(false, 16)),
	CAT_5_CAT_5_IDLE("Cat-5\\Cat-5-Idle.png", new SpriteSheetProperties(false, 16)),
	CAT_5_CAT_5_ITCH("Cat-5\\Cat-5-Itch.png", new SpriteSheetProperties(false, 16)),
	CAT_5_CAT_5_LAYING("Cat-5\\Cat-5-Laying.png", new SpriteSheetProperties(false, 16)),
	CAT_5_CAT_5_LICKING_1("Cat-5\\Cat-5-Licking 1.png", new SpriteSheetProperties(false, 16)),
	CAT_5_CAT_5_LICKING_2("Cat-5\\Cat-5-Licking 2.png", new SpriteSheetProperties(false, 16)),
	CAT_5_CAT_5_MEOW("Cat-5\\Cat-5-Meow.png", new SpriteSheetProperties(false, 16)),
	CAT_5_CAT_5_RUN("Cat-5\\Cat-5-Run.png", new SpriteSheetProperties(false, 16)),
	CAT_5_CAT_5_SITTING("Cat-5\\Cat-5-Sitting.png", new SpriteSheetProperties(false, 16)),
	CAT_5_CAT_5_SLEEPING1("Cat-5\\Cat-5-Sleeping1.png", new SpriteSheetProperties(false, 16)),
	CAT_5_CAT_5_SLEEPING2("Cat-5\\Cat-5-Sleeping2.png", new SpriteSheetProperties(false, 16)),
	CAT_5_CAT_5_STRETCHING("Cat-5\\Cat-5-Stretching.png", new SpriteSheetProperties(false, 16)),
	CAT_5_CAT_5_WALK("Cat-5\\Cat-5-Walk.png", new SpriteSheetProperties(false, 16)),
	CAT_6_CAT_6_IDLE("Cat-6\\Cat-6-Idle.png", new SpriteSheetProperties(false, 16)),
	CAT_6_CAT_6_ITCH("Cat-6\\Cat-6-Itch.png", new SpriteSheetProperties(false, 16)),
	CAT_6_CAT_6_LAYING("Cat-6\\Cat-6-Laying.png", new SpriteSheetProperties(false, 16)),
	CAT_6_CAT_6_LICKING_1("Cat-6\\Cat-6-Licking 1.png", new SpriteSheetProperties(false, 16)),
	CAT_6_CAT_6_LICKING_2("Cat-6\\Cat-6-Licking 2.png", new SpriteSheetProperties(false, 16)),
	CAT_6_CAT_6_MEOW("Cat-6\\Cat-6-Meow.png", new SpriteSheetProperties(false, 16)),
	CAT_6_CAT_6_RUN("Cat-6\\Cat-6-Run.png", new SpriteSheetProperties(false, 16)),
	CAT_6_CAT_6_SITTING("Cat-6\\Cat-6-Sitting.png", new SpriteSheetProperties(false, 16)),
	CAT_6_CAT_6_SLEEPING1("Cat-6\\Cat-6-Sleeping1.png", new SpriteSheetProperties(false, 16)),
	CAT_6_CAT_6_SLEEPING2("Cat-6\\Cat-6-Sleeping2.png", new SpriteSheetProperties(false, 16)),
	CAT_6_CAT_6_STRETCHING("Cat-6\\Cat-6-Stretching.png", new SpriteSheetProperties(false, 16)),
	CAT_6_CAT_6_WALK("Cat-6\\Cat-6-Walk.png", new SpriteSheetProperties(false, 16)),
	CONTROLS("controls.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_ANIMALS_SHEEP_BLACK_SHEEP_DEAD("Fantasy1\\Animals\\Sheep\\Black Sheep Dead.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_ANIMALS_SHEEP_BLACK_SHEEP_IDLE("Fantasy1\\Animals\\Sheep\\Black Sheep Idle.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_ANIMALS_SHEEP_BLACK_SHEEP_SLEEPING("Fantasy1\\Animals\\Sheep\\Black Sheep Sleeping.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_ANIMALS_SHEEP_BLACK_SHEEP_WALKING("Fantasy1\\Animals\\Sheep\\Black Sheep Walking.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_ANIMALS_SHEEP_WHITE_SHEEP_DEAD("Fantasy1\\Animals\\Sheep\\White Sheep Dead.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_ANIMALS_SHEEP_WHITE_SHEEP_IDLE("Fantasy1\\Animals\\Sheep\\White Sheep Idle.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_ANIMALS_SHEEP_WHITE_SHEEP_SLEEPING("Fantasy1\\Animals\\Sheep\\White Sheep Sleeping.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_ANIMALS_SHEEP_WHITE_SHEEP_WALKING("Fantasy1\\Animals\\Sheep\\White Sheep Walking.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_EVENTS_OR_MARKERS_SEVENT_1("Fantasy1\\Events or Markers\\sEvent_1.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_EVENTS_OR_MARKERS_SEVENT_2("Fantasy1\\Events or Markers\\sEvent_2.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_EVENTS_OR_MARKERS_SEVENT_3("Fantasy1\\Events or Markers\\sEvent_3.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_EVENTS_OR_MARKERS_S_EEVENT_1("Fantasy1\\Events or Markers\\s_eEvent_1.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_EVENTS_OR_MARKERS_S_EEVENT_2("Fantasy1\\Events or Markers\\s_eEvent_2.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_EVENTS_OR_MARKERS_S_EEVENT_3("Fantasy1\\Events or Markers\\s_eEvent_3.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_GUI_BARS_BARS("Fantasy1\\GUI\\Bars\\Bars.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_GUI_BARS_HIT_A("Fantasy1\\GUI\\Bars\\Hit-A.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_GUI_BARS_HIT_C("Fantasy1\\GUI\\Bars\\Hit-C.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_GUI_BARS_HIT_D("Fantasy1\\GUI\\Bars\\Hit-D.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_GUI_BARS_LEVEL_A("Fantasy1\\GUI\\Bars\\Level-A.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_GUI_BARS_LEVEL_B("Fantasy1\\GUI\\Bars\\Level-B.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_GUI_BARS_LEVEL_C("Fantasy1\\GUI\\Bars\\Level-C.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_GUI_BARS_LEVEL_D("Fantasy1\\GUI\\Bars\\Level-D.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_GUI_POPUPS_ALERT_BLACK("Fantasy1\\GUI\\Popups\\Alert Black.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_GUI_POPUPS_ALERT_WHITE("Fantasy1\\GUI\\Popups\\Alert White.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_GUI_POPUPS_ARROU_LEFT("Fantasy1\\GUI\\Popups\\Arrou Left.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_GUI_POPUPS_ARROW_DOWN("Fantasy1\\GUI\\Popups\\Arrow Down.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_GUI_POPUPS_ARROW_RIGHT("Fantasy1\\GUI\\Popups\\Arrow Right.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_GUI_POPUPS_ARROW_UP("Fantasy1\\GUI\\Popups\\Arrow Up.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_GUI_POPUPS_POP_UPS("Fantasy1\\GUI\\Popups\\Pop-Ups.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_GUI_POPUPS_QUESTION_MARK_BLACK("Fantasy1\\GUI\\Popups\\Question Mark Black.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_GUI_POPUPS_QUESTION_MARK_WHITE("Fantasy1\\GUI\\Popups\\Question Mark White.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_GUI_TEXT_BOX_NAME_BOX("Fantasy1\\GUI\\Text Box\\Name Box.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_GUI_TEXT_BOX_PORTRAIT_FRAME("Fantasy1\\GUI\\Text Box\\Portrait Frame.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_GUI_TEXT_BOX_TEXTBOX("Fantasy1\\GUI\\Text Box\\Textbox.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_ITEMS_9X9_MINI_ITEMS_PACK("Fantasy1\\Items\\9x9 Mini Items Pack.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_MONSTERS_MONSTER_1_IDLE("Fantasy1\\Monsters\\Monster 1 Idle.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_MONSTERS_MONSTER_1_RUN("Fantasy1\\Monsters\\Monster 1 Run.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_MONSTERS_MONSTER_2_IDLE("Fantasy1\\Monsters\\Monster 2 Idle.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_MONSTERS_MONSTER_2_RUN("Fantasy1\\Monsters\\Monster 2 Run.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_NPCS_BLUE_F1("Fantasy1\\NPCs\\Blue\\F1.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_NPCS_BLUE_F2("Fantasy1\\NPCs\\Blue\\F2.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_NPCS_BLUE_F3("Fantasy1\\NPCs\\Blue\\F3.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_NPCS_BLUE_M1("Fantasy1\\NPCs\\Blue\\M1.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_NPCS_BLUE_M2("Fantasy1\\NPCs\\Blue\\M2.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_NPCS_BLUE_M3("Fantasy1\\NPCs\\Blue\\M3.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_NPCS_BURGUNDY_FK1("Fantasy1\\NPCs\\Burgundy\\FK1.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_NPCS_BURGUNDY_FK2("Fantasy1\\NPCs\\Burgundy\\FK2.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_NPCS_BURGUNDY_FQ3("Fantasy1\\NPCs\\Burgundy\\FQ3.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_NPCS_BURGUNDY_MK1("Fantasy1\\NPCs\\Burgundy\\MK1.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_NPCS_BURGUNDY_MK2("Fantasy1\\NPCs\\Burgundy\\MK2.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_NPCS_BURGUNDY_MK3("Fantasy1\\NPCs\\Burgundy\\MK3.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_NPCS_GREEN_F1("Fantasy1\\NPCs\\Green\\F1.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_NPCS_GREEN_F2("Fantasy1\\NPCs\\Green\\F2.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_NPCS_GREEN_F3("Fantasy1\\NPCs\\Green\\F3.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_NPCS_GREEN_M1("Fantasy1\\NPCs\\Green\\M1.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_NPCS_GREEN_M2("Fantasy1\\NPCs\\Green\\M2.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_NPCS_GREEN_M3("Fantasy1\\NPCs\\Green\\M3.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_PARTICLES_AND_SPELLS_BLUE_ARROW("Fantasy1\\Particles And Spells\\Blue Arrow.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_PARTICLES_AND_SPELLS_BLUE_PARTICLES("Fantasy1\\Particles And Spells\\Blue Particles.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_PARTICLES_AND_SPELLS_COLOR_SHIFTING_PARTICLES("Fantasy1\\Particles And Spells\\Color Shifting Particles.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_PARTICLES_AND_SPELLS_DIRT("Fantasy1\\Particles And Spells\\Dirt.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_PARTICLES_AND_SPELLS_EXPLOSION("Fantasy1\\Particles And Spells\\Explosion.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_PARTICLES_AND_SPELLS_GREEN_ARROW("Fantasy1\\Particles And Spells\\Green Arrow.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_PARTICLES_AND_SPELLS_GREEN_EXPLOSION("Fantasy1\\Particles And Spells\\Green Explosion.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_PARTICLES_AND_SPELLS_GREEN_PARTICLES("Fantasy1\\Particles And Spells\\Green Particles.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_PARTICLES_AND_SPELLS_HIT__BLUE_("Fantasy1\\Particles And Spells\\Hit (Blue).gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_PARTICLES_AND_SPELLS_HIT__GREEN_("Fantasy1\\Particles And Spells\\Hit (Green).gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_PARTICLES_AND_SPELLS_HIT__ORANGE_("Fantasy1\\Particles And Spells\\Hit (Orange).gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_PARTICLES_AND_SPELLS_ICE_WITH_SNOW("Fantasy1\\Particles And Spells\\Ice With Snow.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_PARTICLES_AND_SPELLS_ICE("Fantasy1\\Particles And Spells\\Ice.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_PARTICLES_AND_SPELLS_LIGHT_BLUE_PARTICLES("Fantasy1\\Particles And Spells\\Light Blue Particles.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_PARTICLES_AND_SPELLS_ORANGE_ARROW("Fantasy1\\Particles And Spells\\Orange Arrow.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_PARTICLES_AND_SPELLS_ORANGE_EXPLOSION("Fantasy1\\Particles And Spells\\Orange Explosion.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_PARTICLES_AND_SPELLS_PURPLE_EXPLOSION("Fantasy1\\Particles And Spells\\Purple Explosion.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_PARTICLES_AND_SPELLS_STONE("Fantasy1\\Particles And Spells\\Stone.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_PLACEHOLDERS_SENEMY_1("Fantasy1\\Placeholders\\sEnemy_1.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_PLACEHOLDERS_SENEMY_2("Fantasy1\\Placeholders\\sEnemy_2.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_PLACEHOLDERS_SENEMY_3("Fantasy1\\Placeholders\\sEnemy_3.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_PLACEHOLDERS_SENEMY_4("Fantasy1\\Placeholders\\sEnemy_4.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_PLACEHOLDERS_SENEMY_5("Fantasy1\\Placeholders\\sEnemy_5.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_PLAYER_PLAYER_IDLE("Fantasy1\\Player\\Player Idle.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_PLAYER_PLAYER_JUMP("Fantasy1\\Player\\Player Jump.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_PLAYER_PLAYER_RUN("Fantasy1\\Player\\Player Run.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_PLAYER_PLAYER_SPELL__STILL_("Fantasy1\\Player\\Player Spell (Still).gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_PORTRAITS_NPC_1("Fantasy1\\Portraits\\NPC 1.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_PORTRAITS_NPC_2("Fantasy1\\Portraits\\NPC 2.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_PORTRAITS_NPC_3("Fantasy1\\Portraits\\NPC 3.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_PORTRAITS_NPC_4("Fantasy1\\Portraits\\NPC 4.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_PORTRAITS_NPC_5("Fantasy1\\Portraits\\NPC 5.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_PORTRAITS_PLAYER("Fantasy1\\Portraits\\Player.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_PORTRAITS_UNKNOWN_1("Fantasy1\\Portraits\\Unknown 1.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_PORTRAITS_UNKNOWN_2("Fantasy1\\Portraits\\Unknown 2.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_PORTRAITS_UNKNOWN_3("Fantasy1\\Portraits\\Unknown 3.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_PORTRAITS_UNKNOWN_4("Fantasy1\\Portraits\\Unknown 4.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_PORTRAITS_UNKNOWN_5("Fantasy1\\Portraits\\Unknown 5.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_TILESETS_BASIC_TILES_ONLY("Fantasy1\\Tilesets\\Basic Tiles Only.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_TILESETS_CITY_GROUND_TILESET("Fantasy1\\Tilesets\\City Ground Tileset.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_TILESETS_FIREFLIES_POT_V2("Fantasy1\\Tilesets\\Fireflies pot v2.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_TILESETS_FIREFLIES_POT("Fantasy1\\Tilesets\\Fireflies pot.gif", new SpriteSheetProperties(false, 16)),
	FANTASY1_TILESETS_HOUSE__INSIDE__TILESET("Fantasy1\\Tilesets\\House (Inside) Tileset.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_TILESETS_HOUSE__OUTSIDE_AND_INSIDE__TILESET("Fantasy1\\Tilesets\\House (Outside And Inside) Tileset.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_TILESETS_HOUSE__OUTSIDE__TILESET("Fantasy1\\Tilesets\\House (Outside) Tileset.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_TILESETS_TERRAIN_TILESET("Fantasy1\\Tilesets\\Terrain Tileset.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_TILESETS_VEGETATION_TILESET_1("Fantasy1\\Tilesets\\Vegetation Tileset 1.png", new SpriteSheetProperties(false, 16)),
	FANTASY1_TILESETS_VEGETATION_TILESET_2("Fantasy1\\Tilesets\\Vegetation Tileset 2.png", new SpriteSheetProperties(false, 16)),
	LOADING_BTN01("loading\\Btn01.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ARROW("loading\\Icons\\Arrow.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ARROWS("loading\\Icons\\Arrows.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ARROWS02("loading\\Icons\\Arrows02.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ARROWS03("loading\\Icons\\Arrows03.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ARROWSLEFT("loading\\Icons\\ArrowsLeft.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ARROWSLEFT2("loading\\Icons\\ArrowsLeft2.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ARROWSLEFT3("loading\\Icons\\ArrowsLeft3.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ARROWSRIGHT("loading\\Icons\\ArrowsRight.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ARROWSRIGHT2("loading\\Icons\\ArrowsRight2.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ARROWSRIGHT3("loading\\Icons\\ArrowsRight3.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_CIRCLE01("loading\\Icons\\Circle01.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_CIRCLE02("loading\\Icons\\Circle02.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_CIRCLE03("loading\\Icons\\Circle03.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_CLOSE("loading\\Icons\\Close.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON01("loading\\Icons\\Icon01.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON02("loading\\Icons\\Icon02.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON03("loading\\Icons\\Icon03.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON04("loading\\Icons\\Icon04.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON05("loading\\Icons\\Icon05.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON06("loading\\Icons\\Icon06.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON07("loading\\Icons\\Icon07.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON08("loading\\Icons\\Icon08.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON09("loading\\Icons\\Icon09.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON10("loading\\Icons\\Icon10.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON11("loading\\Icons\\Icon11.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON12("loading\\Icons\\Icon12.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON13("loading\\Icons\\Icon13.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON14("loading\\Icons\\Icon14.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON15("loading\\Icons\\Icon15.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON16("loading\\Icons\\Icon16.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON17("loading\\Icons\\Icon17.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON18("loading\\Icons\\Icon18.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON19("loading\\Icons\\Icon19.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON20("loading\\Icons\\Icon20.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON21("loading\\Icons\\Icon21.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON22("loading\\Icons\\Icon22.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON23("loading\\Icons\\Icon23.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON24("loading\\Icons\\Icon24.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON25("loading\\Icons\\Icon25.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON26("loading\\Icons\\Icon26.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON27("loading\\Icons\\Icon27.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON28("loading\\Icons\\Icon28.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON29("loading\\Icons\\Icon29.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON30("loading\\Icons\\Icon30.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON31("loading\\Icons\\Icon31.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON32("loading\\Icons\\Icon32.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON33("loading\\Icons\\Icon33.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON34("loading\\Icons\\Icon34.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON35("loading\\Icons\\Icon35.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON36("loading\\Icons\\Icon36.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON37("loading\\Icons\\Icon37.png", new SpriteSheetProperties(false, 16)),
	LOADING_ICONS_ICON38("loading\\Icons\\Icon38.png", new SpriteSheetProperties(false, 16)),
	LOADING_PANEL01("loading\\Panel01.png", new SpriteSheetProperties(false, 16)),
	LOADING_PANEL02("loading\\Panel02.png", new SpriteSheetProperties(false, 16)),
	LOADING_PANEL03("loading\\Panel03.png", new SpriteSheetProperties(false, 16)),
	LOADING_PANEL04("loading\\Panel04.png", new SpriteSheetProperties(false, 16)),
	LOADING_PROGRESSBAR_01_BARV1_BAR("loading\\ProgressBar_01\\BarV1_Bar.png", new SpriteSheetProperties(false, 16)),
	LOADING_PROGRESSBAR_01_BARV1_PROGRESSBAR("loading\\ProgressBar_01\\BarV1_ProgressBar.png", new SpriteSheetProperties(false, 16)),
	LOADING_PROGRESSBAR_01_BARV1_PROGRESSBARBORDER("loading\\ProgressBar_01\\BarV1_ProgressBarBorder.png", new SpriteSheetProperties(false, 16)),
	LOADING_PROGRESSBAR_02_BARV2_BAR("loading\\ProgressBar_02\\BarV2_Bar.png", new SpriteSheetProperties(false, 16)),
	LOADING_PROGRESSBAR_02_BARV2_PROGRESSBAR("loading\\ProgressBar_02\\BarV2_ProgressBar.png", new SpriteSheetProperties(false, 16)),
	LOADING_PROGRESSBAR_02_BARV2_PROGRESSBARBORDER("loading\\ProgressBar_02\\BarV2_ProgressBarBorder.png", new SpriteSheetProperties(false, 16)),
	LOADING_PROGRESSBAR_03_BARV3_BAR("loading\\ProgressBar_03\\BarV3_Bar.png", new SpriteSheetProperties(false, 16)),
	LOADING_PROGRESSBAR_03_BARV3_PROGRESSBAR("loading\\ProgressBar_03\\BarV3_ProgressBar.png", new SpriteSheetProperties(false, 16)),
	LOADING_PROGRESSBAR_03_BARV3_PROGRESSBARBORDER("loading\\ProgressBar_03\\BarV3_ProgressBarBorder.png", new SpriteSheetProperties(false, 16)),
	LOADING_PROGRESSBAR_04_BARV4_BAR("loading\\ProgressBar_04\\BarV4_Bar.png", new SpriteSheetProperties(false, 16)),
	LOADING_PROGRESSBAR_04_BARV4_PROGRESSBAR("loading\\ProgressBar_04\\BarV4_ProgressBar.png", new SpriteSheetProperties(false, 16)),
	LOADING_PROGRESSBAR_04_BARV4_PROGRESSBARBORDER("loading\\ProgressBar_04\\BarV4_ProgressBarBorder.png", new SpriteSheetProperties(false, 16)),
	LOADING_PROGRESSBAR_05_BARV5_BAR("loading\\ProgressBar_05\\BarV5_Bar.png", new SpriteSheetProperties(false, 16)),
	LOADING_PROGRESSBAR_05_BARV5_PROGRESSBAR("loading\\ProgressBar_05\\BarV5_ProgressBar.png", new SpriteSheetProperties(false, 16)),
	LOADING_PROGRESSBAR_05_BARV5_PROGRESSBARBORDER("loading\\ProgressBar_05\\BarV5_ProgressBarBorder.png", new SpriteSheetProperties(false, 16)),
	LOADING_PROGRESSBAR_06_BARV6_BAR("loading\\ProgressBar_06\\BarV6_Bar.png", new SpriteSheetProperties(false, 16)),
	LOADING_PROGRESSBAR_06_BARV6_PROGRESSBAR("loading\\ProgressBar_06\\BarV6_ProgressBar.png", new SpriteSheetProperties(false, 16)),
	LOADING_PROGRESSBAR_07_BARV7_BAR("loading\\ProgressBar_07\\BarV7_Bar.png", new SpriteSheetProperties(false, 16)),
	LOADING_PROGRESSBAR_07_BARV7_PROGRESSBAR("loading\\ProgressBar_07\\BarV7_ProgressBar.png", new SpriteSheetProperties(false, 16)),
	LOADING_PROGRESSBAR_07_BARV7_PROGRESSBARBORDER("loading\\ProgressBar_07\\BarV7_ProgressBarBorder.png", new SpriteSheetProperties(false, 16)),
	LOADING_PROGRESSBAR_08_BARV8_BAR("loading\\ProgressBar_08\\BarV8_Bar.png", new SpriteSheetProperties(false, 16)),
	LOADING_PROGRESSBAR_08_BARV8_PROGRESSBAR("loading\\ProgressBar_08\\BarV8_ProgressBar.png", new SpriteSheetProperties(false, 16)),
	LOADING_PROGRESSBAR_09_BARV6_PROGRESSBARBORDER("loading\\ProgressBar_09\\BarV6_ProgressBarBorder.png", new SpriteSheetProperties(false, 16)),
	LOADING_PROGRESSBAR_09_BARV9_BAR("loading\\ProgressBar_09\\BarV9_Bar.png", new SpriteSheetProperties(false, 16)),
	LOADING_PROGRESSBAR_09_BARV9_PROGRESSBAR("loading\\ProgressBar_09\\BarV9_ProgressBar.png", new SpriteSheetProperties(false, 16)),
	MEOW_VFX_MEOW_VFX("Meow-VFX\\Meow-VFX.png", new SpriteSheetProperties(false, 16)),
	POTIONS("potions.png", new SpriteSheetProperties(false, 16)),
	RPG("rpg.png", new SpriteSheetProperties(true, 32)),
	WIZARDPLAYER_ATTACK1("WizardPlayer\\Attack1.png", new SpriteSheetProperties(false, 16)),
	WIZARDPLAYER_ATTACK2("WizardPlayer\\Attack2.png", new SpriteSheetProperties(false, 16)),
	WIZARDPLAYER_DEATH("WizardPlayer\\Death.png", new SpriteSheetProperties(false, 16)),
	WIZARDPLAYER_FALL("WizardPlayer\\Fall.png", new SpriteSheetProperties(false, 16)),
	WIZARDPLAYER_HIT("WizardPlayer\\Hit.png", new SpriteSheetProperties(false, 16)),
	WIZARDPLAYER_IDLE("WizardPlayer\\Idle.png", new SpriteSheetProperties(false, 16)),
	WIZARDPLAYER_JUMP("WizardPlayer\\Jump.png", new SpriteSheetProperties(false, 16)),
	WIZARDPLAYER_RUN("WizardPlayer\\Run.png", new SpriteSheetProperties(false, 16));
    
    private final String dir;
    private BufferedImage image;
    private final SpriteSheetProperties sprite_sheet;
    
    private SpriteSheet(@Nonnull final String dir, @Nonnull final SpriteSheetProperties sprite_sheet) {
        this.dir = dir;
        this.sprite_sheet = sprite_sheet;
    }

    public void setImage(BufferedImage image) {
		this.image = image;
	}

	public String getDir() {
        return dir;
    }

	public BufferedImage getImage() {
		return image;
	}

	public SpriteSheetProperties getProperties() {
		synchronized(this.sprite_sheet) {
			return sprite_sheet;
		}
	}
}